# **Phase 1** (Fundamentals and Array Creation) 

### 1. Import the numpy package under the name np

In [1]:
import numpy as np

### 2. Create a null vector of size 10

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 3. Create a null vector of size 10 but the fifth value which is 1

In [6]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 4. Create a vector with values ranging from 10 to 49

In [14]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 5. Reverse a vector (first element becomes last)

In [23]:
array = np.arange(10)
print(array[::-1])

[9 8 7 6 5 4 3 2 1 0]


### 6. Create a 3x3 matrix with values ranging from 0 to 8 

In [24]:
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 7. Find indices of non-zero elements from [1,2,0,0,4,0]


In [31]:
arr = np.array([1,2,0,0,4,0])

np.where(arr > 0)

(array([0, 1, 4]),)

### 8. Create a 2d array with 1 on the border and 0 inside

In [50]:
arr2d = np.zeros((5,5))
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
arr2d[:,0] = 1
arr2d[:,-1] = 1
arr2d[0,:] = 1
arr2d[-1,:] = 1
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])