# **Phase 2** (Data Manipulation & Broadcasting )

### 9. Normalize a 5x5 random matrix

In [1]:
import numpy as np

matrix = np.random.randint(1,100,25).reshape(5,5)
print(matrix)


[[98 19 60 70 31]
 [42 32 47 80  4]
 [21 30 44  2 15]
 [35 16 26 59 73]
 [50 84 57 62 20]]


In [2]:
min = matrix.min()
max = matrix.max()

normal_matrix = (matrix - min) / (max - min)

print(matrix)
print(normal_matrix)



[[98 19 60 70 31]
 [42 32 47 80  4]
 [21 30 44  2 15]
 [35 16 26 59 73]
 [50 84 57 62 20]]
[[1.         0.17708333 0.60416667 0.70833333 0.30208333]
 [0.41666667 0.3125     0.46875    0.8125     0.02083333]
 [0.19791667 0.29166667 0.4375     0.         0.13541667]
 [0.34375    0.14583333 0.25       0.59375    0.73958333]
 [0.5        0.85416667 0.57291667 0.625      0.1875    ]]


### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [3]:
a1 = np.arange(15).reshape(5,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
a2 = np.arange(6).reshape(3,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
product = np.dot(a1,a2)
product

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

### 11. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [6]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[(arr >= 3) & (arr <=8)] *= -1
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9])

### 12. How to find common values between two arrays?

In [8]:
b1 = np.array([2,5,4,8,7])
b2 = np.array([4,8,0,1,3])

np.intersect1d(b1,b2)

array([4, 8])

### 13. Create a 5x5 matrix with row values ranging from 0 to 4

In [19]:
array = np.arange(5)
array2 = np.zeros((5,5))
array2 + array


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 14. Create a random vector of size 10 and sort it

In [22]:
vector = np.random.randint(0,100,10)
np.sort(vector)

array([17, 32, 44, 46, 48, 49, 61, 70, 71, 94], dtype=int32)

### 15. Consider two random arrays A and B, check if they are equal

In [23]:
r1 = np.random.randint(0,100,10)
r2 = np.random.randint(0,100,10)

r1 == r2

array([False, False, False, False, False, False, False, False, False,
       False])

### 16. Create random vector of size 10 and replace the maximum value by 0

In [33]:
x1 = np.random.randint(0,100,10)
x1

array([70, 62, 41,  9, 30, 11, 12,  4, 40, 78], dtype=int32)

In [34]:
index = np.argmax(x1)
x1[index]  =  0
x1

array([70, 62, 41,  9, 30, 11, 12,  4, 40,  0], dtype=int32)

### 17. How to find the closest value (to a given scalar) in a vector?

In [ ]:
v1 = np.array([10,20,30,40])
scalar = 26

v1[np.argmin(abs(v1 - scalar))]


np.int64(30)

### 18. Subtract the mean of each row of a matrix 

In [64]:
m1 = np.arange(1,10).reshape(3,3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
mean = np.mean(m1,axis=1)
m1 - np.atleast_2d(mean).T


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

### 19. How to sort an array by the nth column?

In [68]:
m2 = np.random.randint(1,100,9).reshape(3,3)
m2

array([[24, 42, 43],
       [66, 74, 55],
       [74, 67, 21]], dtype=int32)

In [72]:
m2[m2[:,2].argsort()]

array([[74, 67, 21],
       [24, 42, 43],
       [66, 74, 55]], dtype=int32)

### 20. How to tell if a given 2D array has null columns? 

In [73]:
n1 = np.array([[1,0,2],
               [4,0,9],
               [6,0,8]])
np.all(n1 == 0, axis=0)

array([False,  True, False])