# NumPy Tricks

## n.sort()

In [2]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([63, 77, 99,  2, 10, 42, 33, 29, 62, 20, 73, 48, 26, 27, 21],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 2,  7,  3, 67],
       [28, 21, 92,  1],
       [61, 60, 56, 28],
       [90, 10,  2, 43],
       [84, 91, 30, 71],
       [10, 14, 53, 10]], dtype=int32)

In [7]:
np.sort(a)[::-1]

array([99, 77, 73, 63, 62, 48, 42, 33, 29, 27, 26, 21, 20, 10,  2],
      dtype=int32)

In [6]:
np.sort(b, axis=0)

array([[ 2,  7,  2,  1],
       [10, 10,  3, 10],
       [28, 14, 30, 28],
       [61, 21, 53, 43],
       [84, 60, 56, 67],
       [90, 91, 92, 71]], dtype=int32)

## np.append

In [8]:
np.append(a,200)

array([ 63,  77,  99,   2,  10,  42,  33,  29,  62,  20,  73,  48,  26,
        27,  21, 200])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[ 2.,  7.,  3., 67.,  1.],
       [28., 21., 92.,  1.,  1.],
       [61., 60., 56., 28.,  1.],
       [90., 10.,  2., 43.,  1.],
       [84., 91., 30., 71.,  1.],
       [10., 14., 53., 10.,  1.]])

## np.concatenate

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique()

In [16]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims

In [17]:
a

array([63, 77, 99,  2, 10, 42, 33, 29, 62, 20, 73, 48, 26, 27, 21],
      dtype=int32)

In [20]:
np.expand_dims(a,axis=1).shape

(15, 1)

## np.where()

In [21]:
a

array([63, 77, 99,  2, 10, 42, 33, 29, 62, 20, 73, 48, 26, 27, 21],
      dtype=int32)

In [22]:
np.where(a > 50)

(array([ 0,  1,  2,  8, 10]),)

In [23]:
np.where(a > 50, 0, a)

array([ 0,  0,  0,  2, 10, 42, 33, 29,  0, 20,  0, 48, 26, 27, 21],
      dtype=int32)

## np.argmax

In [24]:
a

array([63, 77, 99,  2, 10, 42, 33, 29, 62, 20, 73, 48, 26, 27, 21],
      dtype=int32)

In [25]:
np.argmax(a)

np.int64(2)

In [26]:
b

array([[ 2,  7,  3, 67],
       [28, 21, 92,  1],
       [61, 60, 56, 28],
       [90, 10,  2, 43],
       [84, 91, 30, 71],
       [10, 14, 53, 10]], dtype=int32)

In [28]:
np.argmax(b,axis=1)

array([3, 2, 0, 0, 1, 2])

In [29]:
# np.argmin
np.argmin(a)

np.int64(3)

## np.cumsum

In [30]:
a

array([63, 77, 99,  2, 10, 42, 33, 29, 62, 20, 73, 48, 26, 27, 21],
      dtype=int32)

In [31]:
np.cumsum(a)

array([ 63, 140, 239, 241, 251, 293, 326, 355, 417, 437, 510, 558, 584,
       611, 632])

In [32]:
np.cumsum(b, axis=0)

array([[  2,   7,   3,  67],
       [ 30,  28,  95,  68],
       [ 91,  88, 151,  96],
       [181,  98, 153, 139],
       [265, 189, 183, 210],
       [275, 203, 236, 220]])

In [34]:
# np.cumprod
np.cumprod(a)

array([                  63,                 4851,               480249,
                     960498,              9604980,            403409160,
                13312502280,         386062566120,       23935879099440,
            478717581988800,    34946383485182400,  1677426407288755200,
        6719598442088531968, -3038282800705153024, -8463706593679558656])

## np.percentile

In [35]:
a

array([63, 77, 99,  2, 10, 42, 33, 29, 62, 20, 73, 48, 26, 27, 21],
      dtype=int32)

In [38]:
np.percentile(a,50)

np.float64(33.0)

In [39]:
np.median(a)

np.float64(33.0)

## np.histogram

In [40]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 5, 1, 2, 0, 2, 2, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef

In [41]:
salary = np.array([20000,40000,25000,35000,60000])
experiance = np.array([1,3,2,4,2])

np.corrcoef(salary,experiance)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

In [44]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([10, 20], dtype=int32)

## np.flip

In [45]:
np.flip(a)

array([21, 27, 26, 48, 73, 20, 62, 29, 33, 42, 10,  2, 99, 77, 63],
      dtype=int32)

## np.put

In [46]:
np.put(a,[0,1],[110,530])


In [47]:
a

array([110, 530,  99,   2,  10,  42,  33,  29,  62,  20,  73,  48,  26,
        27,  21], dtype=int32)

## np.delete

In [49]:
np.delete(a,[0,2,4])

array([530,   2,  42,  33,  29,  62,  20,  73,  48,  26,  27,  21],
      dtype=int32)

## Set functions

In [50]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
np.intersect1d(m,n)

array([3, 4, 5])

In [52]:
np.setdiff1d(m,n)

array([1, 2])

In [53]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

## np.clip

In [55]:
a

array([110, 530,  99,   2,  10,  42,  33,  29,  62,  20,  73,  48,  26,
        27,  21], dtype=int32)

In [56]:
np.clip(a,a_min= 25, a_max=75)

array([75, 75, 75, 25, 25, 42, 33, 29, 62, 25, 73, 48, 26, 27, 25],
      dtype=int32)