# Creating NumPy / N - D Arrays

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8 = arr7.copy()
arr8


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# NumPy Properties and Attributes

In [11]:
arr1

array([1, 2, 3, 4])

In [12]:
arr1.shape

(4,)

In [13]:
arr2.shape

(2, 3)

In [14]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
arr9.shape

(2, 2, 2)

In [16]:
arr9.ndim

3

In [17]:
arr1.ndim

1

In [18]:
arr1.size

4

In [19]:
arr9.size

8

In [20]:
arr9.itemsize

8

In [21]:
arr8.itemsize

8

In [22]:
arr8.dtype

dtype('float64')

In [23]:
arr9.dtype

dtype('int64')

- Changing type

In [24]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [25]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
np.random.random((3,2))

array([[0.77837591, 0.47485716],
       [0.63028443, 0.6613754 ],
       [0.22970346, 0.59295204]])

# Array Operations

In [27]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

- Scalar Operations

In [28]:
# Arithmetic 
a1 * 2 # Mathematical Operators can be used + - / % **

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
# Relational Operators
a2 > 15 # == >= <= > < != !

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

- Vector Operations

In [30]:
a1 + a2 # + - / % * **

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Functions

In [31]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[71.,  4., 58.],
       [55., 40., 95.],
       [16., 15.,  4.]])

- Max / Min / Sum / Product

In [32]:
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

print(np.min(a1, axis=1)) # For  row/column (axis = 0 -> Column | axis = 1 -> Row)
print(np.sum(a1, axis=1))

95.0
4.0
358.0
3304942080000.0
[ 4. 40.  4.]
[133. 190.  35.]


- Statistcal Operations

In [33]:
# mean, median, std -> Standard Deviation, var -> Variance
np.mean(a1)
np.mean(a1, axis = 1)

array([44.33333333, 63.33333333, 11.66666667])

- Trignometric funtions

In [34]:
np.sin(a1) # All other Trignometric functions

array([[ 0.95105465, -0.7568025 ,  0.99287265],
       [-0.99975517,  0.74511316,  0.68326171],
       [-0.28790332,  0.65028784, -0.7568025 ]])

- Dot Product

In [35]:
# Simply multiplication of 2 matrices (If the number of cols of one matrix == number of rows of other)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

- Log and Exponents

In [36]:
np.log(a1)

array([[4.26267988, 1.38629436, 4.06044301],
       [4.00733319, 3.68887945, 4.55387689],
       [2.77258872, 2.7080502 , 1.38629436]])

In [37]:
np.exp(a1)

array([[6.83767123e+30, 5.45981500e+01, 1.54553894e+25],
       [7.69478527e+23, 2.35385267e+17, 1.81123908e+41],
       [8.88611052e+06, 3.26901737e+06, 5.45981500e+01]])

- Round / Floor and Ceil

In [38]:
np.round(np.random.random((2,3)) * 100)

array([[62., 83., 83.],
       [83., 84., 33.]])

In [39]:
np.floor(np.random.random((2,3)) * 100)

array([[ 2., 70., 30.],
       [42., 84., 53.]])

In [40]:
np.ceil(np.random.random((2,3)) * 100)

array([[20., 42., 94.],
       [68., 13., 16.]])

# Indexing and Slicing

In [41]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[1,2]

np.int64(6)

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a3[0,1,0]

np.int64(2)

In [49]:
# Slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2] #a1[2:5]

array([2, 4])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a2[0,:]

array([0, 1, 2, 3])

In [54]:
a2[:,2]

array([ 2,  6, 10])

In [55]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [56]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [57]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [62]:
a2[1,0::3]

array([4, 7])

In [65]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
a3[0,1,:]

array([3, 4, 5])

In [69]:
a3[1,:,1]

array([10, 13, 16])

In [70]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [75]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [76]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [78]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [79]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [80]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [81]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [83]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# Ravel -> converts to 1 d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [90]:
# Horizontal Stacking            # Shape must be same for stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [91]:
# Horizontal Splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]